### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by Kirb101** [Vinetos/java-portable#3]
(idk how to add labels but this is a `bug`)
## Host system: Windows 11 Home

Hey. I'm trying to go from Windows 11 to 10. I can't install portable java and I like to keep everything portable.
.\setup.ps1 doesn't work (I enabled scripts and ran it as Administrator). Also does this install JDK 18? Here's what PowerShell 7 showed:

![image](https://github.com/Vinetos/java-portable/assets/78144805/b5704fda-2251-4444-bee7-65fb4ac44bbe)

```Get LessMSI
Expand LessMSI
Get 7-Zip
Use LessMSI to unpack 7zip
Extracting 'F:\java-portable-master\7z2201-x64.msi' to 'F:\java-portable-master\7z2201-x64'.

Error: System.IO.IOException: Failed to open Windows Installer database: F:\java-portable-master\7z2201-x64.msi
   at Microsoft.Tools.WindowsInstallerXml.Msi.Database.Open(String path, OpenDatabase type)
   at LessMsi.Msi.MsiFile.CreateMsiFilesFromMSI(String msiDatabaseFilePath)
   at LessMsi.Msi.Wixtracts.GetMsiFileFromFileNames(FileInfo msi, String[] fileNamesToExtract)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, List`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)

Usage:
lessmsi <command> [options] <msi_name> [<path_to_extract\>] [file_names]

Commands:
  x  Extracts all or specified files from the specified msi_name.
  l  Lists the contents of the specified msi table as CSV to stdout.
  v  Lists the value of the ProductVersion Property in the msi
     (typically this is the version of the MSI).
  o  Opens the specified msi_name in the GUI.
  h  Shows this help page.

For more information see http://lessmsi.activescott.com

Detected 64bit OS, switching...
Download Java JDK jdk-8u341-windows-x64
Invoke-WebRequest: F:\java-portable-master\Setup.ps1:96
Line |
  96 |  …             Invoke-WebRequest -Uri $Url -OutFile $OutFile -UserAgent  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The format of value '[Microsoft.PowerShell.Commands.PSUserAgent]::FireFox' is invalid.
Unpack JDK installer
&: F:\java-portable-master\Setup.ps1:104
Line |
 104 |              & ".\$7zDirectory\$7zExecutable"                      `
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '.\.\7z2201-x64\SourceDir\Files\7-Zip\7z.exe' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Unpack JDK archive
&: F:\java-portable-master\Setup.ps1:115
Line |
 115 |          & ".\$7zDirectory\$7zExecutable"     `
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '.\.\7z2201-x64\SourceDir\Files\7-Zip\7z.exe' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Unpack JDK
&: F:\java-portable-master\Setup.ps1:121
Line |
 121 |      & ".\$7zDirectory\$7zExecutable" 'x' $OracleJDKInternalArchive `
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '.\.\7z2201-x64\SourceDir\Files\7-Zip\7z.exe' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Expand JDK files

    Directory: F:\java-portable-master

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          17/06/2024    07:54            366 start.bat

Done.```

**Comment by sergeevabc** [comment]
Windows 7 user here.
I confirm that the current version of PS1 script does not work.
